[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "dipanshuchaubey",email = "41301181+dipanshuchaubey@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard] (>=0.136.3,<0.137.0)",
    "firebase-admin (>=7.4.0,<8.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
